# Generated by Django 4.2.3 on 2023-07-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPoligonosTexto',
            fields=[
                ('id_poligono', models.IntegerField(primary_key=True, serialize=False)),
                ('id_distrito', models.SmallIntegerField()),
                ('nombre_distrito', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=100)),
                ('id_seccion', models.IntegerField()),
                ('nombre_seccion', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=254)),
                ('score_promedio', models.FloatField()),
                ('q_geo', models.BigIntegerField()),
                ('indice_geo', models.DecimalField(decimal_places=4, max_digits=24)),
                ('q_estimada', models.DecimalField(decimal_places=4, max_digits=28)),
                ('q_personaspriorizadas', models.BigIntegerField()),
                ('indice_hogares', models.FloatField()),
                ('hogares_estimados', models.FloatField()),
                ('observado', models.BooleanField()),
                ('shape_texto', models.TextField()),
            ],
        ),
    ]
